# <https://wiki.sponsor.ajay.app/w/Types>
categories=sponsor,selfpromo,interaction,intro,outro,preview,hook,filler
skip_categories=sponsor,selfpromo,interaction,intro,outro,preview,hook,filler
skip_once=yes
report_views=no