[options]
view_style = 'adaptive'
show_quality_monitor = 'Y'
show_remote_cursor = 'Y'
i444 = 'Y'
image_quality = 'custom'
custom-fps = '120.0'
custom_image_quality = '2000.0'
disable_audio = 'Y'
zoom-cursor = 'Y'