# High Quality
profile=high-quality
glsl-shader="~~/FSRCNNX_x2_16-0-4-1.glsl"
glsl-shader="~~/KrigBilateral.glsl"

# Player
fs=yes
keep-open=yes
hr-seek=yes
keep-open-pause=no
auto-window-resize=no
osd-bar-border-size=0.5
image-display-duration=0.4
input-default-bindings=no
watch-later-options-remove=pause

# Demuxer
demuxer-max-bytes=1GiB
demuxer-max-back-bytes=1GiB
directory-mode=recursive
autocreate-playlist=filter

# OSD
osd-bar-align-y=-0.98
osd-border-size=1
osd-font-size=30

# Audio
alang=ja,en
volume-max=100

# Video
hwdec=auto
hwdec-threads=0
video-sync=display-resample

# Subtitles
sub-auto=fuzzy
sub-fonts-dir=Fonts
sub-file-paths=Subs;eng;sub

# Screenshot
screenshot-format=png
screenshot-png-filter=0
screenshot-png-compression=0

# YouTube
ytdl-raw-options=mark-watched=,playlist-end=100

# Profiles
[Switch from FSRCNNX x16 to FSRCNNX x8]
profile-cond=p["frame-drop-count"]>30 or p["mistimed-frame-count"]>30 or p["vo-delayed-frame-count"]>30
glsl-shaders-remove="~~/FSRCNNX_x2_16-0-4-1.glsl"
glsl-shaders-remove="~~/KrigBilateral.glsl"
glsl-shader="~~/FSRCNNX_x2_8-0-4-1.glsl"
glsl-shader="~~/KrigBilateral.glsl"

[Turn off FSRCNNX x8 and KrigBilateral]
profile-cond=p["frame-drop-count"]>60 or p["mistimed-frame-count"]>60 or p["vo-delayed-frame-count"]>60
glsl-shaders-remove="~~/FSRCNNX_x2_8-0-4-1.glsl"
glsl-shaders-remove="~~/KrigBilateral.glsl"

[Gamma 2.2]
profile-cond = get("video-params/colormatrix") == "bt.709"
treat-srgb-as-power22=auto
target-trc=gamma2.2
target-contrast=3500

# [BT.1886]
# profile-cond = get("video-params/colormatrix") == "bt.709"
# treat-srgb-as-power22=no
# target-trc=bt.1886
# target-contrast=3500

[HDR]
profile-cond = get("video-params/colormatrix") == "bt.2020-ncl"
treat-srgb-as-power22=no
target-trc=pq
target-peak=700